### ISSUE TITLE
Build Breaker Hangs Up

### ISSUE THREAD

**Issue by jbdundas** [adnovum/sonar-build-breaker#26]
Hi,

The build breaker plugin is taking a long time to finish, almost 3 hours. can you help us find the root cause. Even after the CE side finished the processing, it still keeps waiting.

Another point - There is another project which goes through which is 10 times the source code size on the same Build Breaker plugin without any issues.

![image](https://user-images.githubusercontent.com/4275521/29275395-f9f3a21e-80d8-11e7-9058-adf5c56661ad.png)

Why does that happen and what can we do to fix this?

Configuration:-
------------------
Linux , JDK8 , Jenkins , SonarQube 5.6.5,  Sonar Build Breaker 2.2 

https://github.com/SonarQubeCommunity/sonar-build-breaker/releases/download/2.2/sonar-build-breaker-plugin-2.2.jar
------------------
One more possibility - we drilled down to the code and found that it is blocked at the Thread.sleep line in the GateQualityBreaker.java file.  

Can you please fix this bug? It looks like it may be affecting a lot of folks since 2 applications on our side are already facing this issue at hand. Perhaps we can replace the Thread.sleep call with a TimerTask/Timer function ( or any other way) since Thread.sleep is known to cause problems in certain environments. Also, it is not recommended to use in some code these days

Thanks,
Jitesh

**Comment by sandro-h** [comment]
Hey @jbdundas, very late answer (we've since taken over maintainership of the plugin). I'll hazard a guess and say this is probably no longer relevant. In the meantime SonarQube is at version 7.9, and we've also just released a new version of the sonar-build-breaker which supports it.
I'll therefore close this issue, but feel free to comment if you still encounter such problems with newer versions.
