### ISSUE TITLE
sonarqube doesnot mark the status as failed while reporting issues.

### ISSUE THREAD

**Issue by jacknblak** [adnovum/sonar-build-breaker#32]
In my case i have integrated sonar-github-plugin to comment the status in PR, 

**Problem Description:**
sonarqube reports the issues as expected, however it doesn't mark the status as "Failed" when it report the issues.

**Screenshot**
![image](https://user-images.githubusercontent.com/22939777/38084289-e994ac3a-3369-11e8-81e4-c049e2051d6f.png)

**My Expectation**
i expect it to mark the status as failed with X mark 
![image](https://user-images.githubusercontent.com/22939777/38085119-0e12c0ee-336d-11e8-8344-d611cc59b1a6.png) instead of marking it as success with tick mark
![image](https://user-images.githubusercontent.com/22939777/38085127-1a899c80-336d-11e8-95cb-c7d830485c18.png)

**Comment by sandro-h** [comment]
Hey @jacknblak, late answer (we've since taken over maintainership of this plugin). I'm not sure if this is related to the sonar-build-breaker plugin. All it does is fail the build on the client side if the analysis failed the quality gate. This happens at the very end without the Sonar server knowing what the build-breaker is doing. The sonar-github-plugin probably reports based on the server status (i.e. the quality gate status on the server).
Anyway, since then, the sonar-github-plugin has been deprecated and archived. SonarQube has built-in support for interactions with various SCM tools now.
