### ISSUE TITLE
Build Breaker Plugin not working as expected

### ISSUE THREAD

**Issue by rakeshs2123** [adnovum/sonar-build-breaker#33]
i have enabled build breaker plugin but its not working as expected.

20:37:13.171 INFO: Quality gate status: ERROR
20:37:13.179 ERROR: Coverage on New Code: 73.33333333333333 > 70
20:37:13.179 ERROR: [BUILD BREAKER] Project did not meet 1 conditions
20:37:13.208 INFO: ------------------------------------------------------------------------
20:37:13.208 INFO: EXECUTION FAILURE
20:37:13.208 INFO: ------------------------------------------------------------------------

**Comment by sandro-h** [comment]
Hey @rakeshs2123, very late answer (we've since taken over maintainership of the plugin): it's hard to say what doesn't work as expected based on your output. The plugin breaks the build because the project did not pass the quality gate (which apparently is configured on your server to expect 70% or more coverage on new code).
I suggest to update to the latest plugin version and if it still doesn't run the way you expect, please let me know what your expected outcome vs actual outcome is.
