### ISSUE TITLE
Error when executing task

### ISSUE THREAD

**Issue by jcrecio** [adnovum/sonar-build-breaker#40]
I´m running a build process in VSTS and all the sonar qube steps work properly (prepare, run, so on) except for the break build.
![1](https://user-images.githubusercontent.com/2377872/47644544-bab35300-db6e-11e8-8fa0-2a83201e49ec.PNG)
![2](https://user-images.githubusercontent.com/2377872/47644552-bf780700-db6e-11e8-9afa-8595afb38d3d.PNG)

Any idea??

Thanks in advance.

**Comment by sandro-h** [comment]
Hey @jcrecio, late answer (we've since taken over maintainership of the plugin). In the meantime SonarQube is at version 7.9, and we've also just released a new version of the sonar-build-breaker which supports it.
I'll close this issue since it's quite old, but if you do still encounter these problems (also with up-to-date SonarQube and sonar-build-breaker versions), do let me know.
